### ISSUE TITLE
Laravel 5 is stable now

### ISSUE THREAD

**Issue by jonasvanderhaegen** [fitztrev/laravel-html-minify#48] opened 2015-02-04 16:17 UTC
Wanted to let you know Laravel 5 is stable now, could you make a L5 package for this?

**Comment by GrahamCampbell** [comment] 2015-02-04 18:24
I maintain L5 package similar to this that provides a lot more stuff too.

It feels wrong to "poach" users, but if this package isn't being actively maintained, then there's little else to do.

**Comment by fitztrev** [comment] 2015-02-04 19:42
Thanks, will update soon. Pull requests welcome in the meantime. :smile:

**Comment by dhardtke** [comment] 2015-02-18 02:35
+1

**Comment by gantoo** [comment] 2015-02-24 15:07
@fitztrev nice work

**Comment by yocmen** [comment] 2015-02-25 21:09
i made all changes for L5 compatibility, if u need any help just write me.

**Comment by fitztrev** [comment] 2015-02-25 21:10
@yocmen Would you like to open a pull request?

**Comment by yocmen** [comment] 2015-02-25 21:13
yes, of course, but let me see how do that first, i don't know how work
github, im new in this.

2015-02-25 16:40 GMT-04:30 Trevor Fitzgerald <notifications@github.com>:

> @yocmen <https://github.com/yocmen> Would you like to open a pull request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/fitztrev/laravel-html-minify/issues/48#issuecomment-76059192>
> .
>



-- 

  Pensemos en el medio ambiente. Imprime sólo lo necesario.

**Comment by canfiax** [comment] 2015-02-26 19:36
is it merged? is l5 support done?

**Comment by NgYueHong** [comment] 2015-03-02 10:25
I'm looking for Laravel 5 support as well.

**Comment by hackel** [comment] 2015-06-18 03:19
@yocmen Any update on creating a pull request for this?  I see your package is not actually registered as a fork in Github.  You need to create an actual fork by clicking on the fork button above, then merge the changes from your branch into the fork, and push back to Github.  At that point, you will be able to create the pull request from the Github website.

**Comment by fitztrev** [comment] 2015-06-23 12:57
Read my preferred way of minifying HTML in Laravel 5/5.1+ apps here: [Using Gulp to Minify Laravel Blade Templates](https://github.com/fitztrev/laravel-html-minify/wiki/Laravel-5---5.1-HTML-Minifying)

**Closed by fitztrev** 2015-06-23 12:57 UTC

**Comment by hackel** [comment] 2015-06-24 02:03
@fitztrev pre-minification of blade templates really doesn't make sense at all, as the html files are not yet generated.  A lot of excess whitespace can be caused by @foreach loops and such, not to mention other php code within them.  Also, the gulpfile you linked to is overwriting the actual blade templates with minified versions! At the very least, one should have a separate directory for editing the non-minified template files so that formatting is preserved.  The whole point of minification is to allow the original files to remain verbosely formatted for readability.

Perhaps a better solution would be to integrate minification with some kind of reverse proxy like Varnish.

**Comment by fitztrev** [comment] 2015-06-24 02:08
@hackel I have a separate routine that goes through and pre-compiles my blade templates for me, compiling them to the storage/cache directory.

> Also, the gulpfile you linked to is overwriting the actual blade templates with minified versions!

No, it's not. It's only minifying the compiled views.
